import { test, expect } from '@playwright/test'

test('deep merge matches nested IDs, except skips queries, always survives exclusion and reset replaces state', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const first = await page.goto('/advanced')
  expect((await first!.text()).includes('data-server-rendered="true"')).toBe(process.env.INERTIA_EXPECT_CSR !== 'true')
  await expect(page.getByTestId('preferences')).toHaveText('light / en')
  await expect(page.getByTestId('members').locator('li')).toHaveText(['1: Ada', '2: Linus'])
  const before = Number((await page.getByTestId('expensive').textContent())!.split(': ')[1])
  await expect(page.getByTestId('optional')).toHaveText('Optional query: not loaded')
  for (let attempt = 0; attempt < 2; attempt++) {
    const pending = page.waitForResponse(r => r.url().includes('/advanced') && r.request().headers()['x-inertia-partial-data'] === 'profile')
    await page.getByRole('button', { name: 'Merge profile delta', exact: true }).click()
    const response = await pending
    const delta = await response.json()
    expect(delta.props.profile.name).toBeUndefined()
    expect(delta.props.profile.preferences.language).toBeUndefined()
    expect(delta.deepMergeProps).toEqual(['profile'])
    expect(delta.matchPropsOn).toEqual(['profile.members.id'])
    await expect(page.getByTestId('profile-name')).toHaveText('Ada')
    await expect(page.getByTestId('preferences')).toHaveText('dark / en')
    await expect(page.getByTestId('members').locator('li')).toHaveText(['1: Ada', '2: Linus updated', '3: Grace'])
  }
  const except = page.waitForResponse(r => r.url().includes('/advanced') && r.request().headers()['x-inertia-partial-except'] === 'expensive,profile,status')
  await page.getByRole('button', { name: 'Reload except profile and query', exact: true }).click()
  const omitted = await (await except).json()
  expect(omitted.props.expensive).toBeUndefined()
  expect(omitted.props.profile).toBeUndefined()
  expect(omitted.props.status).toBe(2)
  // The Rust adapter selects every non-excluded prop on an except-only visit,
  // including optional callbacks. Java intentionally preserves that contract.
  expect(omitted.props.optional).toBe(1)
  expect(omitted.deepMergeProps).toBeUndefined()
  await expect(page.getByTestId('optional')).toHaveText('Optional query: 1')
  await expect(page.getByTestId('expensive')).toHaveText(`Expensive query: ${before}`)
  await expect(page.getByTestId('always-status')).toHaveText('Always phase: 2')
  await page.getByRole('button', { name: 'Run expensive query', exact: true }).click()
  await expect(page.getByTestId('expensive')).toHaveText(`Expensive query: ${before + 1}`)
  await page.getByRole('button', { name: 'Load optional query', exact: true }).click()
  await expect(page.getByTestId('optional')).toHaveText('Optional query: 2')
  const reset = page.waitForResponse(r => r.url().includes('/advanced') && r.request().headers()['x-inertia-reset'] === 'profile')
  await page.getByRole('button', { name: 'Reset profile', exact: true }).click()
  const replaced = await (await reset).json()
  expect(replaced.deepMergeProps).toBeUndefined()
  expect(replaced.matchPropsOn).toBeUndefined()
  await expect(page.getByTestId('preferences')).toHaveText('light / en')
  await expect(page.getByTestId('members').locator('li')).toHaveText(['1: Ada', '2: Linus'])
  await expect(page.getByTestId('expensive')).toHaveText(`Expensive query: ${before + 1}`)
  expect(errors).toEqual([])
})

test('same-name fields use independent named error bags and do not replay after successful forms', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/advanced')
  const personal = page.getByRole('form', { name: 'Profile form', exact: true })
  const team = page.getByRole('form', { name: 'Team form', exact: true })
  const profileRequest = page.waitForRequest(r => r.method() === 'POST' && r.url().endsWith('/advanced/profile'))
  await personal.getByRole('button', { name: 'Save profile', exact: true }).click()
  expect((await profileRequest).headers()['x-inertia-error-bag']).toBe('profile')
  await expect(personal.getByRole('alert')).toHaveText('Enter a profile name.')
  await expect(team.getByRole('alert')).toHaveCount(0)
  const teamRequest = page.waitForRequest(r => r.method() === 'POST' && r.url().endsWith('/advanced/team'))
  await team.getByRole('button', { name: 'Save team', exact: true }).click()
  expect((await teamRequest).headers()['x-inertia-error-bag']).toBe('team')
  await expect(team.getByRole('alert')).toHaveText('Enter a team name.')
  await expect(personal.getByRole('alert')).toHaveText('Enter a profile name.')
  await personal.getByLabel('Profile name', { exact: true }).fill('Ada')
  await personal.getByRole('button', { name: 'Save profile', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('profile saved (demo only)')
  await expect(personal.getByRole('alert')).toHaveCount(0)
  await expect(team.getByRole('alert')).toHaveText('Enter a team name.')
  await team.getByLabel('Team name', { exact: true }).fill('Core')
  await team.getByRole('button', { name: 'Save team', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('team saved (demo only)')
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.getByRole('status')).toHaveCount(0)
  expect(errors).toEqual([])
})
