import { test, expect } from '@playwright/test'

test('identity boundary rotates session and CSRF, rejects stale logout and protects account', async ({ page, context }) => {
  test.skip(process.env.INERTIA_EXPECT_AUTH !== 'true', 'Opt-in identity demonstration only')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const response = await page.goto('/login')
  const html = await response!.text()
  expect(html.includes('data-server-rendered="true"')).toBe(process.env.INERTIA_EXPECT_CSR !== 'true')
  await expect(page).toHaveTitle('Sign in')
  const before = await context.cookies()
  const oldCsrf = before.find(cookie => cookie.name === 'XSRF-TOKEN')!.value
  const oldSession = before.find(cookie => cookie.name === 'JSESSIONID')!.value
  await page.getByLabel('Username', { exact: true }).fill('demo')
  await page.getByLabel('Password', { exact: true }).fill('incorrect-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Sign-in failed. Check your credentials and try again.')
  await expect(page.getByLabel('Password', { exact: true })).toHaveValue('')
  await page.getByLabel('Password', { exact: true }).fill('local-demo-test-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByTestId('identity')).toHaveText('Signed in as demo')
  const after = await context.cookies()
  expect(after.find(cookie => cookie.name === 'JSESSIONID')!.value).not.toBe(oldSession)
  expect(after.find(cookie => cookie.name === 'XSRF-TOKEN')!.value).not.toBe(oldCsrf)
  const document = await page.request.get('/account')
  expect(document.status()).toBe(200)
  if (process.env.INERTIA_EXPECT_CSR !== 'true') expect(await document.text()).toContain('Signed in as <!-- -->demo')
  await page.route('**/logout', async route => {
    await route.continue({ headers: { ...route.request().headers(), 'x-xsrf-token': oldCsrf } })
  }, { times: 1 })
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Your security token changed. Review your form and submit again.')
  await expect(page.getByTestId('identity')).toHaveText('Signed in as demo')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page).toHaveTitle('Sign in')
  const denied = page.waitForResponse(r => r.url().endsWith('/account') && r.status() === 409)
  await page.getByRole('link', { name: 'Open protected account' }).click()
  expect((await denied).headers()['x-inertia-location']).toBe('/login')
  await expect(page).toHaveTitle('Sign in')
  expect(errors).toEqual([])
})

test('logout clears account in another tab and encrypted back history', async ({ page, context }) => {
  test.skip(process.env.INERTIA_EXPECT_AUTH !== 'true', 'Opt-in identity demonstration only')
  await page.goto('/login')
  await page.getByLabel('Username', { exact: true }).fill('demo')
  await page.getByLabel('Password', { exact: true }).fill('local-demo-test-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByTestId('identity')).toBeVisible()
  await page.getByRole('link', { name: 'Public users' }).click()
  await expect(page).toHaveTitle('Users')
  await page.goBack()
  await expect(page.getByTestId('identity')).toHaveText('Signed in as demo')
  await page.getByRole('link', { name: 'Public users' }).click()
  await expect(page).toHaveTitle('Users')
  const other = await context.newPage()
  await other.goto('/account')
  await expect(other.getByTestId('identity')).toBeVisible()
  await other.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(other).toHaveTitle('Sign in')
  await expect(page).toHaveTitle('Sign in')
  await expect(page.getByTestId('identity')).toHaveCount(0)
  await page.goBack()
  await expect(page).toHaveURL(/\/login$/)
  await expect(page).toHaveTitle('Sign in')
  await expect(page.getByTestId('identity')).toHaveCount(0)
  await other.close()
})

test('real container idle expiry denies protected navigation and permits a fresh login', async ({ page, context }) => {
  test.skip(process.env.INERTIA_EXPECT_AUTH_EXPIRY !== 'true', 'Real one-minute servlet session scenario only')
  test.setTimeout(100000)
  await page.goto('/login')
  await page.getByLabel('Username', { exact: true }).fill('demo')
  await page.getByLabel('Password', { exact: true }).fill('local-demo-test-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByTestId('identity')).toBeVisible()
  const oldSession = (await context.cookies()).find(cookie => cookie.name === 'JSESSIONID')!.value
  await page.getByRole('link', { name: 'Public users' }).click()
  // This is deliberately real elapsed time: browser clock controls cannot expire Tomcat sessions.
  await new Promise(resolve => setTimeout(resolve, 65000))
  await page.goto('/login')
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  expect((await context.cookies()).find(cookie => cookie.name === 'JSESSIONID')!.value).not.toBe(oldSession)
  const denied = page.waitForResponse(r => r.url().endsWith('/account') && r.status() === 409)
  await page.getByRole('link', { name: 'Open protected account' }).click()
  await denied
  await expect(page).toHaveTitle('Sign in')
  await page.getByLabel('Username', { exact: true }).fill('demo')
  await page.getByLabel('Password', { exact: true }).fill('local-demo-test-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByTestId('identity')).toHaveText('Signed in as demo')
})
