import { test, expect } from '@playwright/test'

test('SSR hydration, navigation, deferred data, validation and flash', async ({ page, request }) => {
  test.skip(process.env.INERTIA_EXPECT_CSR === 'true', 'SSR test runs only with renderer connected')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text() + ' ' + message.location().url) })
  const first = await request.get('/users')
  expect(await first.text()).toContain('data-server-rendered="true"')
  expect(await first.text()).toContain('<li>Ada</li>')
  await page.goto('/users')
  await expect(page).toHaveTitle('Users')
  await expect(page.getByTestId('stats')).toHaveText('Total: 2')
  await expect(page.getByTestId('large-id')).toHaveText('Exact ID: 9007199254740993')
  const navigation = page.waitForResponse(r => r.url().endsWith('/about') && r.request().headers()['x-inertia'] === 'true')
  await page.getByRole('link', { name: 'About this app' }).click()
  expect((await navigation).headers()['content-type']).toContain('application/json')
  await expect(page).toHaveTitle('About')
  await page.getByRole('link', { name: 'Back to users' }).click()
  const mutation = page.waitForRequest(r => r.method() === 'POST' && r.url().endsWith('/users'))
  await page.getByRole('button', { name: 'Save demo name' }).click()
  expect((await mutation).headers()['x-xsrf-token']).toBeTruthy()
  await expect(page.getByRole('alert')).toHaveText('Please enter a name.')
  await page.getByLabel('Name', { exact: true }).fill('Grace')
  await page.getByRole('button', { name: 'Save demo name' }).click()
  await expect(page.getByRole('status')).toHaveText('Saved Grace (demo only)')
  await page.screenshot({ path: '/tmp/inertia-java-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '/tmp/inertia-java-mobile.png', fullPage: true })
  expect(errors).toEqual([])
})

test('CSR fallback mounts and can navigate when SSR is disconnected', async ({ page }) => {
  test.skip(process.env.INERTIA_EXPECT_CSR !== 'true', 'Run against Java with an unavailable SSR endpoint')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const response = await page.goto('/users')
  expect(await response!.text()).not.toContain('data-server-rendered')
  await expect(page.getByTestId('stats')).toHaveText('Total: 2')
  await page.getByRole('link', { name: 'About this app' }).click()
  await expect(page).toHaveTitle('About')
  expect(errors).toEqual([])
})

test('infinite scroll prepend/append/reset and once reuse/refresh', async ({ page }) => {
  test.skip(process.env.INERTIA_EXPECT_CSR === 'true', 'Advanced flow runs in SSR mode')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/feed?page=2')
  await expect(page).toHaveTitle('Feed')
  const items = page.getByTestId('feed-items').getByRole('listitem')
  await expect(items).toHaveCount(3)
  const firstCatalog = await page.getByTestId('catalog').textContent()
  await page.getByRole('button', { name: 'Load previous', exact: true }).click()
  await expect(items).toHaveCount(6)
  await expect(items.first()).toHaveText('Item 1')
  await page.getByRole('button', { name: 'Load next', exact: true }).click()
  await expect(items).toHaveCount(9)
  await expect(items.last()).toHaveText('Item 9')
  await page.getByRole('button', { name: 'Reset feed' }).click()
  await expect(items).toHaveCount(3)
  await expect(items.first()).toHaveText('Item 1')
  await page.getByRole('link', { name: 'About this app' }).click()
  await page.getByRole('link', { name: 'Explore feed' }).click()
  await expect(page.getByTestId('catalog')).toHaveText(firstCatalog!)
  await page.getByRole('button', { name: 'Refresh catalog' }).click()
  await expect(page.getByTestId('catalog')).not.toHaveText(firstCatalog!)
  expect(errors).toEqual([])
})
