import { test, expect } from '@playwright/test'

test('SSR hydration, navigation, deferred data, validation and flash', async ({ page, request }) => {
  test.skip(process.env.INERTIA_EXPECT_CSR === 'true', 'SSR test runs only with renderer connected')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text() + ' ' + message.location().url) })
  const first = await request.get('/users')
  expect(await first.text()).toContain('data-server-rendered="true"')
  expect(await first.text()).toContain('<li>Ada</li>')
  await page.goto('/users')
  await expect(page).toHaveTitle('Users')
  await expect(page.getByTestId('stats')).toHaveText('Total: 2')
  await expect(page.getByTestId('large-id')).toHaveText('Exact ID: 9007199254740993')
  const navigation = page.waitForResponse(r => r.url().endsWith('/about') && r.request().headers()['x-inertia'] === 'true')
  await page.getByRole('link', { name: 'About this app' }).click()
  expect((await navigation).headers()['content-type']).toContain('application/json')
  await expect(page).toHaveTitle('About')
  await page.getByRole('link', { name: 'Back to users' }).click()
  const mutation = page.waitForRequest(r => r.method() === 'POST' && r.url().endsWith('/users'))
  await page.getByRole('button', { name: 'Save demo name' }).click()
  expect((await mutation).headers()['x-xsrf-token']).toBeTruthy()
  await expect(page.getByRole('alert')).toHaveText('Please enter a name.')
  await page.getByLabel('Name', { exact: true }).fill('Grace')
  await page.getByRole('button', { name: 'Save demo name' }).click()
  await expect(page.getByRole('status')).toHaveText('Saved Grace (demo only)')
  await page.screenshot({ path: '/tmp/inertia-java-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '/tmp/inertia-java-mobile.png', fullPage: true })
  expect(errors).toEqual([])
})

test('CSR fallback mounts and can navigate when SSR is disconnected', async ({ page }) => {
  test.skip(process.env.INERTIA_EXPECT_CSR !== 'true', 'Run against Java with an unavailable SSR endpoint')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const response = await page.goto('/users')
  expect(response!.status()).toBe(200)
  const html = await response!.text()
  expect(html).not.toContain('data-server-rendered')
  expect(html).toContain('<div id="app"></div>')
  await expect(page.getByTestId('stats')).toHaveText('Total: 2')
  await page.getByRole('link', { name: 'About this app' }).click()
  await expect(page).toHaveTitle('About')
  await page.getByRole('link', { name: 'Back to users' }).click()
  await page.getByRole('button', { name: 'Save demo name' }).click()
  await expect(page.getByRole('alert')).toHaveText('Please enter a name.')
  await page.getByLabel('Name', { exact: true }).fill('Grace')
  await page.getByRole('button', { name: 'Save demo name' }).click()
  await expect(page.getByRole('status')).toHaveText('Saved Grace (demo only)')
  expect(errors).toEqual([])
})

test('infinite scroll prepend/append/reset and once reuse/refresh', async ({ page }) => {
  test.skip(process.env.INERTIA_EXPECT_CSR === 'true', 'Advanced flow runs in SSR mode')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/feed?page=2')
  await expect(page).toHaveTitle('Feed')
  const items = page.getByTestId('feed-items').getByRole('listitem')
  await expect(items).toHaveCount(3)
  const firstCatalog = await page.getByTestId('catalog').textContent()
  await page.getByRole('button', { name: 'Load previous', exact: true }).click()
  await expect(items).toHaveCount(6)
  await expect(items.first()).toHaveText('Item 1')
  await page.getByRole('button', { name: 'Load next', exact: true }).click()
  await expect(items).toHaveCount(9)
  await expect(items.last()).toHaveText('Item 9')
  await page.getByRole('button', { name: 'Reset feed' }).click()
  await expect(items).toHaveCount(3)
  await expect(items.first()).toHaveText('Item 1')
  await page.getByRole('link', { name: 'About this app' }).click()
  await page.getByRole('link', { name: 'Explore feed' }).click()
  await expect(page.getByTestId('catalog')).toHaveText(firstCatalog!)
  await page.getByRole('button', { name: 'Refresh catalog' }).click()
  await expect(page.getByTestId('catalog')).not.toHaveText(firstCatalog!)
  expect(errors).toEqual([])
})


test('all-errors server mode preserves and displays every field message', async ({ page }) => {
  test.skip(process.env.INERTIA_EXPECT_ALL_ERRORS !== 'true', 'Run Java with --inertia.all-errors=true')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/users')
  await expect(page.getByTestId('stats')).toHaveText('Total: 2')
  await page.getByLabel('Name', { exact: true }).fill('<' + 'x'.repeat(100))
  const redirectedPage = page.waitForResponse(r => r.url().endsWith('/users') && r.headers()['content-type']?.includes('application/json') === true && r.request().redirectedFrom()?.method() === 'POST')
  await page.getByRole('button', { name: 'Save demo name' }).click()
  const payload = await (await redirectedPage).json()
  expect(payload.props.errors.name).toEqual(expect.arrayContaining(['Name must be at most 100 characters.', 'Name must not contain angle brackets.']))
  const messages = page.getByRole('alert').getByRole('listitem')
  await expect(messages).toHaveCount(2)
  await expect(messages).toHaveText(payload.props.errors.name)
  await page.getByLabel('Name', { exact: true }).fill('Grace')
  await page.getByRole('button', { name: 'Save demo name' }).click()
  await expect(page.getByRole('status')).toHaveText('Saved Grace (demo only)')
  await expect(page.getByRole('alert')).toHaveCount(0)
  expect(errors).toEqual([])
})


test('safe error page preserves status, hydrates or mounts, and recovers by navigation', async ({ page, request }) => {
  test.skip(process.env.INERTIA_EXPECT_FAILURES !== 'true', 'Run Java with --inertia.demo-failures=true')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const response = await page.goto('/failures/props')
  expect(response!.status()).toBe(500)
  const html = await response!.text()
  expect(html).not.toContain('Demo data source failure')
  if (process.env.INERTIA_EXPECT_CSR !== 'true') expect(html).toContain('data-server-rendered="true"')
  await expect(page.getByRole('heading', { name: 'Error 500' })).toBeVisible()
  await expect(page).toHaveTitle('Error 500')
  await page.getByRole('link', { name: 'Back to users' }).click()
  await expect(page).toHaveTitle('Users')
  await expect(page.getByTestId('stats')).toHaveText('Total: 2')
  const invalidated = await page.goto('/failures/session')
  expect(invalidated!.status()).toBe(500)
  await expect(page.getByRole('heading', { name: 'Error 500' })).toBeVisible()
  await page.getByRole('link', { name: 'Back to users' }).click()
  await expect(page.getByTestId('stats')).toHaveText('Total: 2')
  const initialPage = JSON.parse(html.match(/<script[^>]*data-page=\"app\"[^>]*>([\s\S]*?)<\/script>/)![1])
  const forbidden = await request.get('/failures/forbidden', { headers: { 'X-Inertia': 'true', 'X-Inertia-Version': initialPage.version } })
  expect(forbidden.status()).toBe(403)
  expect((await forbidden.json()).props.status).toBe(403)
  expect(await forbidden.text()).not.toContain('Demo denial')
  expect(errors).toEqual([])
})
