import { test, expect } from '@playwright/test'

test('history encryption, response opt-out, key clearing and per-page CSR', async ({ page }) => {
  test.skip(process.env.INERTIA_EXPECT_HISTORY !== 'true', 'Run the opt-in history harness')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const first = await page.goto('/demo-history/encrypted')
  expect(await first!.text()).toContain('data-server-rendered')
  await expect(page.getByTestId('history-mode')).toHaveText('encrypted')
  await expect.poll(() => page.evaluate(() => history.state?.page instanceof ArrayBuffer)).toBe(true)
  expect(await page.evaluate(() => Boolean(window.crypto.subtle))).toBe(true)
  const initialVisits = await page.getByTestId('history-visits').textContent()
  const plainResponse = page.waitForResponse(r => r.url().endsWith('/demo-history/plain') && r.request().headers()['x-inertia'] === 'true')
  await page.getByRole('link', { name: 'plain', exact: true }).click()
  expect((await (await plainResponse).json()).encryptHistory).toBeUndefined()
  await expect(page.getByTestId('history-mode')).toHaveText('plain')
  await expect.poll(() => page.evaluate(() => history.state?.page?.props?.marker)).toBe('demo-history-marker')
  await page.goBack()
  await expect(page.getByTestId('history-mode')).toHaveText('encrypted')
  await expect(page.getByTestId('history-visits')).toHaveText(initialVisits!)
  await page.goForward()
  await expect(page.getByTestId('history-mode')).toHaveText('plain')
  await page.getByRole('link', { name: 'encrypted', exact: true }).click()
  await expect(page.getByTestId('history-mode')).toHaveText('encrypted')
  const beforeClear = Number(await page.getByTestId('history-visits').textContent())
  await expect.poll(() => page.evaluate(() => history.state?.page instanceof ArrayBuffer)).toBe(true)
  const clearedResponse = page.waitForResponse(r => r.url().endsWith('/demo-history/clear') && r.request().headers()['x-inertia'] === 'true')
  await page.getByRole('link', { name: 'clear', exact: true }).click()
  expect((await (await clearedResponse).json()).clearHistory).toBe(true)
  await expect(page.getByTestId('history-mode')).toHaveText('clear')
  await expect.poll(() => page.evaluate(() => history.state?.page instanceof ArrayBuffer)).toBe(true)
  const refreshed = page.waitForResponse(r => r.url().endsWith('/demo-history/encrypted'))
  await page.goBack()
  expect((await refreshed).ok()).toBe(true)
  await expect(page.getByTestId('history-mode')).toHaveText('encrypted')
  await expect.poll(async () => Number(await page.getByTestId('history-visits').textContent())).toBeGreaterThan(beforeClear)
  const csr = await page.goto('/demo-history/csr')
  const html = await csr!.text()
  expect(html).not.toContain('data-server-rendered')
  expect(html).toContain('<div id="app"></div>')
  await expect(page.getByTestId('history-mode')).toHaveText('csr')
  await page.getByRole('link', { name: 'encrypted', exact: true }).click()
  await expect(page.getByTestId('history-mode')).toHaveText('encrypted')
  expect(errors).toEqual([])
})
