<?xml version="1.0" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.inertia</groupId>
    <artifactId>inertia-java</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>inertia-testing</artifactId>
  <properties>
    <inertia.javadoc.doclint>all</inertia.javadoc.doclint>
    <inertia.javadoc.fail-on-warnings>true</inertia.javadoc.fail-on-warnings>
  </properties>
  <dependencies>
    <dependency>
      <groupId>io.inertia</groupId>
      <artifactId>inertia-core</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
</project>
